### ISSUE TITLE
PG3 not updating

### ISSUE THREAD

**Issue by mrwkbrdr** [BME-nodeservers/docs#3]
Edit: removed log
I have noticed since PG3 that almost every other day I have to restart the this node in order for it to once again start communciating and populating data in IOP. 

This node server was rock solid on PG2 and I never once had to restart it?

Any help would be greatly appreciatted. 

Log attached.

**Comment by bpaauwe** [comment]
Looks like it had a bug when processing the query command, but that shouldn't have stopped it from getting status updates.

However, I also see this a couple of time:
_Failed to get status of mower: HTTPSConnectionPool(host='amc-api.dss.husqvarnagroup.net', port=443): Max retries exceeded with url: /app/v1/mowers/201016595-200650216/status_
Which could mean that your shortpoll time is too short causing the Husqvarna server to rate limit.  In this case, you won't be getting any status until it allows connections again.

I did fix the query issue and pushed a new version 2.0.1

If you refresh the store, you should see this version and restarting the node server will auto-update to it.

**Comment by mrwkbrdr** [comment]
Followed your direction and now running 2.0.1. Both of my short and long polls are 60. I will monitor over the next week and report back the results. Really appreciatte your fast response and great support.

**Comment by mrwkbrdr** [comment]
Once again no communication with IOP. 
Log file attached.
[HusqvarnaMower_6-11-2022_120121_PM.zip](https://github.com/BME-nodeservers/docs/files/8884297/HusqvarnaMower_6-11-2022_120121_PM.zip)

**Comment by bpaauwe** [comment]
There's nothing in the log to indicate that anything is wrong.  The last entry (well all entries are) is:

2022-06-11 12:01:00,933 Thread-2119 udi_interface      INFO     mower:get_status: Connection to mower is True

Since I don't know your timezone I don't know if that corresponds with when you downloaded the log or not. But this indicates that at that time, it was able to communicate with the server and get the current status of the mower. 

If you turned on debug level logging, it would show what was received with the query for mower status each poll interval.  It might help by showing what it thinks it's sending to the ISY.  I can't tell from the log (not enough info there), but it kind of looks like it's not updating the ISY because nothing on the mower has changed.  Debug log level would confirm this.

Can you explain what you mean by "no communication with IOP"?  

You aren't by chance rebooting the IOP every day are you?  The node server won't send updates if the data hasn't changed and if the IOP is rebooted, since its not getting any updates from the node server, it may leave all the fields blank until it does.

**Comment by mrwkbrdr** [comment]
My definition of "no communication" is the "node server online" is blank instead of true. When the node server online is blank, then no data is populated in the node for Automower. 

No I do not re-boot my IOP everyday. I have had to re-boot IOP but not in the last few weeks.

My time zone is EDT.

Debug log attached.
[HusqvarnaMower_6-11-2022_32749_PM.zip](https://github.com/BME-nodeservers/docs/files/8884612/HusqvarnaMower_6-11-2022_32749_PM.zip)
[HusqvarnaMower_6-11-2022_32901_PM.zip](https://github.com/BME-nodeservers/docs/files/8884615/HusqvarnaMower_6-11-2022_32901_PM.zip)

These debug logs were captured after the node was restarted earlier today, and at the time of capture the node online was true.

**Comment by bpaauwe** [comment]
I see nothing wrong in any of the log files.

The PG3 log shows it communicating with the node server and the node server never changes the on-line status.  The node server log shows it communicating with the Husqvarna server without any issues.

After you turned on debug, I see 2 queries to the server with proper data being returned.  I'm assuming it was working at that point.  

During the time periods covered by all the logs you've sent, I don't see the anything changing on the mower and as I mentioned, if nothing changes, nothing is sent to the IOP.  Only when something changes will it be sent.  The exception to that is when the node server is started it will send everything and I do see that happening when you restart the node server.

I see nothing at all wrong with the node server operation.  What you get on the admin console is based on communication between the admin console and the ISY.  The node server doesn't have anything to do with that.   Blank values on the admin console usually mean that the value is unknown to the admin console. Either the ISY hasn't sent anything to the admin console or the admin console hasn't queried the ISY for that information.   In many cases, this can happen if the ISY is restarted and nothing is changing in the node server.  The node server doesn't know the ISY was restarted and thus the ISY never gets a values until something changes. Until that point it is unknown.  That sounds like what is happening here, which is why I asked about rebooting the ISY.  

The node server never sends a value that would result in a blank value for on-line status, it sends either a 1 or 0 which is displayed as True or False.  Even if the node server stopped sending any updates to the ISY, it would keep the last value sent.  The only case I know of that can result in a blank field is a restart of the ISY as I explained above.

The only thing I have left to suggest is to keep it running with debug enabled and when you notice it being blank, note the time frame and I can check the node server log and verify if it is still running fine during that time period.

**Comment by mrwkbrdr** [comment]
Update:

I changed nothing since previous comment, and mower did not run for 3 days.
The node server has stayed online "true" for 3 days now. Excellent!

Thank you.
